# Generated by Django 2.1.5 on 2019-03-28 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerBranch',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ไอดีเจ้าของสาขา')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='branches.Branch', verbose_name='สาขา')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 3}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของ')),
            ],
            options={
                'db_table': 'owner',
            },
        ),
    ]
