# Generated by Django 2.2.1 on 2019-05-25 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmachine',
            name='next_fix',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 9, 43, 45, 858067), verbose_name='การซ่อมครั้งถัดไป'),
        ),
    ]
