# Generated by Django 2.2.1 on 2019-05-29 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20190525_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmachine',
            name='next_fix',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 8, 30, 17, 416798), verbose_name='การซ่อมครั้งถัดไป'),
        ),
    ]
