# Generated by Django 2.1.5 on 2019-03-26 09:43

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ไอดีผู้ใช้')),
                ('username', models.CharField(help_text='ไม่เกิน20ตัวอักษร เป็นตัวอักษรภาษาอังกฤษ ผสมกับตัวเลขได้', max_length=20, unique=True, verbose_name='ชื่อผู้ใช้')),
                ('password', models.CharField(help_text='รหัสผ่านขั้นต่ำ8ตัวอักษร เป็นตัวอักษรภาษาอังกฤษ ผสมกับตัวเลขได้', max_length=100, verbose_name='รหัสผ่าน')),
                ('organization', models.CharField(blank=True, help_text='ไม่เกิน30ตัวอักษร', max_length=30, null=True, verbose_name='ชื่อ องค์กร')),
                ('email', models.EmailField(help_text='ตัวอย่างเช่น user@email.com', max_length=50, unique=True)),
                ('user_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'แอดมิน'), (2, 'พนักงาน'), (3, 'เจ้าของกิจการ'), (4, 'ช่างซ่อม')], null=True, verbose_name='สถานะผู้ใช้งาน')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
