# Generated by Django 2.1.5 on 2019-03-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False, verbose_name='IDสาขา')),
                ('branch_img', models.ImageField(help_text='ชื่อไฟล์ไม่เกิน60ตัวอักษร', max_length=60, upload_to='owner/', verbose_name='รูปถ่ายสาขา')),
                ('branch_name', models.CharField(help_text='ไม่เกิน20ตัวอักษร', max_length=20, unique=True, verbose_name='ชื่อสถานที่')),
                ('branch_address', models.CharField(max_length=50, verbose_name='เลขที่อยู่')),
                ('branch_district', models.CharField(max_length=30, verbose_name='ตำบล')),
                ('branch_amphoe', models.CharField(max_length=30, verbose_name='อำเภอ')),
                ('branch_province', models.CharField(max_length=30, verbose_name='จังหวัด')),
                ('branch_zipcode', models.CharField(max_length=5, verbose_name='รหัสไปรษณีย์')),
                ('branch_postcode', models.CharField(help_text='รหัสไปรษณีย์ ตามด้วยลำดับสาขา 01-99(ห้ามซ้ำ)', max_length=7, unique=True, verbose_name='รหัสสาขา')),
                ('tel_number', models.CharField(max_length=10, verbose_name='เบอร์โทรศัพท์1')),
                ('tel_number_two', models.CharField(blank=True, max_length=10, null=True, verbose_name='เบอร์โทรศัพท์2')),
                ('tel_number_three', models.CharField(blank=True, max_length=10, null=True, verbose_name='เบอร์โทรศัพท์3')),
            ],
            options={
                'verbose_name': 'จัดการสาขา',
                'verbose_name_plural': 'จัดการสาขา',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='BranchWithdraw',
            fields=[
                ('withdraw_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ไอดีการบันทึกเงิน')),
                ('branch_check_date', models.DateTimeField(auto_now=True, verbose_name='เช็ควันที่')),
                ('branch_check_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='branches.Branch', verbose_name='สาขา')),
            ],
            options={
                'verbose_name': 'บันทึกการเก็บเงินของสาขา',
                'verbose_name_plural': 'บันทึกการเก็บเงินของสาขา',
                'db_table': 'branch_money',
            },
        ),
    ]
