# Generated by Django 2.2.1 on 2019-05-29 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0003_auto_20190529_0830'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now=True, verbose_name='เช็ควันที่')),
                ('check_update', models.DateTimeField(auto_now_add=True, verbose_name='วันที่แก้ไข')),
                ('check_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('fix_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ค่าซ่อม')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='branches.BranchWithdraw', verbose_name='สาขา')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='machines.BranchMachine', verbose_name='เครื่อง')),
            ],
        ),
    ]
