# Generated by Django 2.1.5 on 2019-03-26 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='faqsite',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ไอดีคำถาม/ตอบ')),
                ('question', models.CharField(max_length=100, verbose_name='คำถาม')),
                ('answered', models.CharField(max_length=100, verbose_name='คำตอบ')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='managesite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='ชื่อไฟล์ไม่เกิน60ตัวอักษร', max_length=60, upload_to='site_manage/', verbose_name='ไอคอนเว็บไซต์')),
                ('brand', models.CharField(help_text='ไม่เกิน20ตัวอักษร', max_length=20, verbose_name='ชื่อไซต์')),
                ('welcome', models.TextField(verbose_name='ข้อความต้อนรับ')),
                ('about', models.CharField(help_text='ไม่เกิน100ตัวอักษร', max_length=100, verbose_name='เกี่ยวกับเรา')),
                ('service', models.TextField(verbose_name='การให้บริการ')),
                ('contact', models.CharField(help_text='ไม่เกิน100ตัวอักษร', max_length=100, verbose_name='ติดต่อเรา')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'index_site',
            },
        ),
        migrations.CreateModel(
            name='serviceimg',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ไอดีรูป')),
                ('img', models.ImageField(help_text='ชื่อไฟล์ไม่เกิน60ตัวอักษร', max_length=60, upload_to='site_manage/service', verbose_name='รูปภาพ')),
                ('detail', models.CharField(help_text='ไม่เกิน60ตัวอักษร', max_length=20, verbose_name='คำอธิบาย')),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_img',
            },
        ),
    ]
