# Generated by Django 2.2.1 on 2019-05-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimg',
            name='detail',
            field=models.CharField(help_text='ไม่เกิน60ตัวอักษร', max_length=60, verbose_name='คำอธิบาย'),
        ),
    ]
